# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 07:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('start_time', models.DateTimeField()),
                ('duration_time', models.DurationField()),
                ('rank', models.TextField(default='{}')),
                ('last_submit_id', models.IntegerField(default=0)),
                ('private', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('proid', models.AutoField(primary_key=True, serialize=False)),
                ('originoj', models.CharField(max_length=10)),
                ('problemid', models.CharField(max_length=10)),
                ('problemurl', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('timelimit', models.CharField(max_length=50)),
                ('memorylimit', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('sampleinput', models.TextField()),
                ('sampleoutput', models.TextField()),
                ('updatetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('runid', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('lang', models.IntegerField(blank=True, null=True)),
                ('result', models.CharField(max_length=50)),
                ('timec', models.CharField(blank=True, max_length=50, null=True)),
                ('memoryc', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.DateTimeField()),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vj.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='info', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('school', models.CharField(blank=True, max_length=50)),
                ('sid', models.CharField(blank=True, max_length=50)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('problem_ac', models.IntegerField(default=0)),
                ('problem_try', models.IntegerField(default=0)),
                ('problems_ac', models.ManyToManyField(related_name='aceduser', to='vj.Problem')),
                ('problems_try', models.ManyToManyField(related_name='trieduser', to='vj.Problem')),
            ],
        ),
        migrations.AddField(
            model_name='status',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contest',
            name='accounts',
            field=models.ManyToManyField(blank=True, related_name='accessable_contests', to='vj.UserInfo'),
        ),
        migrations.AddField(
            model_name='contest',
            name='problems',
            field=models.ManyToManyField(related_name='contests', to='vj.Problem'),
        ),
        migrations.AddField(
            model_name='contest',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
